---
- name: Install required packages
  apt:
    name: certbot
    state: present
- name: Fetch certificate
  command: "certbot certonly --standalone --noninteractive --text --agree-tos --preferred-challenges http --email {{certbot_email }} --domains {{keycloak_hostname }}"
- name: Create directory accessible to Keycloak
  file:
    path: /opt/keycloak-certs
    state: directory
    owner: keycloak
    group: keycloak
- name: Copy cert file to certs directory
  copy:
    src: "/etc/letsencrypt/live/{{ keycloak_hostname }}/fullchain.pem"
    dest: "{{ keycloak_cert_dir }}/fullchain.pem"
    remote_src: yes
- name: Copy private key file to certs directory
  copy:
    src: "/etc/letsencrypt/live/{{ keycloak_hostname }}/privkey.pem"
    dest: "{{ keycloak_cert_dir }}/privkey.pem"
    remote_src: yes
- name: Create certificate renewal hook
  template:
    src: cert-renewal.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/cert-renewal.sh
    mode: 0755

