---
- name: Install PotgreSQL required packages
  apt:
    pkg: 
      - postgresql
      - python3-pip
      - python3-psycopg2 # required to use 'postgresql_db' module
    state: present
- name: Create Keycloak database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    state: present
- name: Create Keycloak DB user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
- name: Grant Keycloak DB user access to database
  become: yes
  become_user: postgres
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: true
    privs: all
- name: Grant all permissions on public schema
  become: yes
  become_user: postgres
  postgresql_privs:
    database: "{{ db_name }}"
    privs: ALL
    type: schema
    objs: public
    roles: "{{ db_user }}"
